export const FETCH_ARTICLE = "ARTICLE/FETCH_ARTICLE";

export const SET_ARTICLE = "ARTICLE/SET_ARTICLES";
export const SET_FETCHING_ARTICLE = "ARTICLE/SET_FETCHING_ARTICLE";
export const SET_ARTICLE_ERROR = "ARTICLE/SET_ARTICLE_ERROR";
