export const FETCH_ARTICLES = "HOME/FETCH_ARTICLES";

export const SET_ARTICLES = "HOME/SET_ARTICLES";
export const SET_FETCHING_ARTICLES = "HOME/SET_FETCHING_ARTICLES";
export const SET_ARTICLES_ERROR = "HOME/SET_ARTICLES_ERROR";
